// Auth
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOG_OUT = 'LOG_OUT';
export const VERFY_TOKEN = 'VERFY_TOKEN';
export const STEP_1_COMPLETED = 'STEP_1_COMPLETED';
export const STEP_2_COMPLETED = 'STEP_2_COMPLETED';

// Me
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const SAVE_PERSONAL_INFO = 'SAVE_PERSONAL_INFO';
export const SET_CURRENT_AVATAR_PROFILE = 'SET_CURRENT_AVATAR_PROFILE';
export const SET_CURRENT_COVER_PROFILE = 'SET_CURRENT_COVER_PROFILE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAN_USER = 'CLEAN_USER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_COVER_PROFILE = 'UPDATE_COVER_PROFILE';
export const UPDATE_AVATAR_PROFILE = 'UPDATE_AVATAR_PROFILE';

// Professions
export const FETCH_PROFESSIONS = 'FETCH_PROFESSIONS';
export const UPDATE_CHOSEN_PROFESSION = 'UPDATE_CHOSEN_PROFESSION';
export const SAVE_SELECTED_PROFESSIONS = 'SAVE_SELECTED_PROFESSIONS';

// App
export const INITIALIZED = 'INITIALIZED';
export const CHANGE_NET_STATUS = 'CHANGE_NET_STATUS';
export const CHANGE_APP_STATE = 'CHANGE_APP_STATE';
export const CHANGE_TUTORIAL_STATE = 'CHANGE_TUTORIAL_STATE';

// Notifications
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';

// Ads
export const FETCH_ADS = 'FETCH_ADS';
export const FETCH_MY_ADS = 'FETCH_MY_ADS';
export const SET_CURRENT_AD = 'SET_CURRENT_AD';
export const REMOVE_AD_BY_ID = 'REMOVE_AD_BY_ID';
export const CREATE_AD = 'CREATE_AD';


// Locations
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';

