// Auth
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const VERFY_TOKEN = 'VERFY_TOKEN';

// Me
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const SAVE_PERSONAL_INFO = 'SAVE_PERSONAL_INFO';

// Professions
export const FETCH_PROFESSIONS = 'FETCH_PROFESSIONS';
export const UPDATE_CHOSEN_PROFESSION = 'UPDATE_CHOSEN_PROFESSION';
export const SAVE_SELECTED_PROFESSIONS = 'SAVE_SELECTED_PROFESSIONS';

// App
export const INITIALIZED = 'INITIALIZED';
export const CHANGE_NET_STATUS = 'CHANGE_NET_STATUS';
export const CHANGE_APP_STATE = 'CHANGE_APP_STATE';
export const CHANGE_TUTORIAL_STATE = 'CHANGE_TUTORIAL_STATE';
