# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'plartApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for plartApp
  # pod 'IQKeyboardManager'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'plartAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'plartApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for plartApp-tvOS

  target 'plartApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
